version: "3"

services:
  axolotl:
    build: .
    # stdin_open: true # -i
    # tty: true # -t
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./lora.yml:/workspace/axolotl/lora.yml
      - ./datasets/:/workspace/datasets/
      - ./models/:/workspace/models/
      - ./out/:/workspace/out/
      - ./last_run_prepared/:/workspace/last_run_prepared/
      - ./huggingface/:/root/.cache/huggingface/
      # Axolotl Patch
      - ./patch/axolotl/data.py:/workspace/axolotl/src/axolotl/utils/data.py
    environment:
      - HF_HUB_OFFLINE=1
    # environment:
    #   - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
    #   - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
    #   - GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME}
    #   - GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL}
      # - WANDB_API_KEY=${WANDB_API_KEY}
    command: launch finetune.py lora.yml
