version: "3"

services:
  axolotl:
    build: .
    # stdin_open: true # -i
    # tty: true # -t

    privileged: true
    ipc: host
    shm_size: 10g
    ulimits:
      memlock: -1
      stack: 67108864
    
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./lora.yml:/workspace/axolotl/lora.yml
      - ./datasets/:/workspace/datasets/
      - ./models/:/workspace/models/
      - ./out/:/workspace/out/
      - ./last_run_prepared/:/workspace/last_run_prepared/
      - ./huggingface/:/root/.cache/huggingface/
      # Axolotl Patch
      - ./patch/axolotl/data.py:/workspace/axolotl/src/axolotl/utils/data.py
    environment:
      - HF_HUB_OFFLINE=1
      # temporary fix for https://github.com/intel/compute-runtime/issues/710
      - NEOReadDebugKeys=1
      - OverrideGpuAddressSpace=48
      # use A770
      - ONEAPI_DEVICE_SELECTOR=level_zero:0
    # entrypoint: sycl-ls
    # command: 
    command: launch finetune.py lora.yml
