version: "3"

services:
  axolotl:
    build: .
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./lora.yml:/workspace/axolotl/lora.yml
      - ./datasets/:/workspace/datasets/
      - ./out/:/workspace/out/
      - ./huggingface/:/root/.cache/huggingface/
    environment:
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
      - GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME}
      - GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL}
      # - WANDB_API_KEY=${WANDB_API_KEY}